### ISSUE TITLE
exception during dart-oss-licenses

### ISSUE THREAD

**Issue by smiLLe** [ko2ic/dart_oss_licenses#1]
Error Package List:
"sky_engine","flutter","flutter_test","flutter_localizations",
Unhandled exception:
Assertion failed
#0      SettingsBundlePlistFormat.write (file:///Users/myuser/.pub-cache/hosted/pub.dartlang.org/dart_oss_licenses-0.5.1/bin/formats/settings_bundle_plist_format.dart:59:7)
<asynchronous suspension>
#1      main.<anonymous closure> (file:///Users/myuser/.pub-cache/hosted/pub.dartlang.org/dart_oss_licenses-0.5.1/bin/main.dart:56:18)
<asynchronous suspension>
#2      List.forEach (dart:core/runtime/libgrowable_array.dart:274:8)
#3      main (file:///Users/myuser/.pub-cache/hosted/pub.dartlang.org/dart_oss_licenses-0.5.1/bin/main.dart:55:14)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#8      Future._complete (dart:async/future_impl.dart:476:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:292:13)
#12     LicenseHttpClient.fetchLicense (file:///Users/myuser/.pub-cache/hosted/pub.dartlang.org/dart_oss_licenses-0.5.1/bin/http/license_http_client.dart)
#13     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#17     Future._complete (dart:async/future_impl.dart:476:7)
#18     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#19     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#20     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:292:13)
#21     _withClient (package:http/http.dart)
#22     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#30     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#31     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#32     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

**Comment by dyson-yamashita** [comment]
I had same exception. I resolved by createing Settings.bundle directory.
dart-oss-licenses create files in <Project directory>/ios/Runner/Settings.bundle.
Does Setting.bundle directory exists ?
If none, you create etting.bundle directory.

settings_bundle_plist_format.dart 
> '${environmentVars["PWD"]}/ios/Runner/Settings.bundle';
